@echo off
echo Initiating Bazaar Uptime Shield...
echo Purging dead shells...
docker rm -f Bazaar-Main-Node testnet2
echo Anchoring v19.9 Captive-Core...
docker run -d --name Bazaar-Main-Node --restart always -p 31401:31401 -p 31402:31402 -p 31403:31403 pinetwork/pi-node-docker:latest --testnet2 --enable-auto-migrations
echo MESH-SCAN Complete. Node anchored for Feb 27 Protocol.
pause